# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create!(name: 'Emanuel', city: cities.first)

MainClass.transaction do
  main_class = MainClass.create!(:name => "nine")
  section_a = main_class.sections.create!(:name => "a")
  section_b = main_class.sections.create!(:name => "b")
  section_a.users.create!([{:name => "student1"}, {:name => "student2"}, {:name => "student3"}, {:name => "student4"}, {:name => "student5"}, {:name => "student6"}, {:name => "student7"}, {:name => "student8"}, {:name => "student9"}, {:name => "student10"}])
  section_b.users.create!([{:name => "student11"}, {:name => "student12"}, {:name => "student13"}, {:name => "student14"}, {:name => "student15"}, {:name => "student16"}, {:name => "student17"}, {:name => "student18"}, {:name => "student19"}, {:name => "student20"}])
  fa1 = MainTest.create!(:name => "fa1")
  fa2  = MainTest.create!(:name => "fa2")
  sa1 = MainTest.create!(:name => "sa1")

  student1 = User.find_by_name("student1")
  student2 = User.find_by_name("student2")
  student3 = User.find_by_name("student3")
  student4 = User.find_by_name("student4")
  student5 = User.find_by_name("student5")
  student6 = User.find_by_name("student6")
  student7 = User.find_by_name("student7")
  student8 = User.find_by_name("student8")
  student9 = User.find_by_name("student9")
  student10 = User.find_by_name("student10")
  student11 = User.find_by_name("student11")
  student12 = User.find_by_name("student12")
  student13 = User.find_by_name("student13")
  student14 = User.find_by_name("student14")
  student15 = User.find_by_name("student15")
  student16 = User.find_by_name("student16")
  student17 = User.find_by_name("student17")
  student18 = User.find_by_name("student18")
  student19 = User.find_by_name("student19")
  student20 = User.find_by_name("student20")

  [fa1,fa2,sa1].each do |test|
    case test.name
    when "fa1"
      student1.test_results.create!(:main_test_id => test.id, :marks => 45)
      student2.test_results.create!(:main_test_id => test.id, :marks => 85)
      student3.test_results.create!(:main_test_id => test.id, :marks => 70)
      student4.test_results.create!(:main_test_id => test.id, :marks => 71)
      student5.test_results.create!(:main_test_id => test.id, :marks => 76)
      student6.test_results.create!(:main_test_id => test.id, :marks => 71)
      student7.test_results.create!(:main_test_id => test.id, :marks => 68)
      student8.test_results.create!(:main_test_id => test.id, :marks => 56)
      student9.test_results.create!(:main_test_id => test.id, :marks => 43)
      student10.test_results.create!(:main_test_id => test.id, :marks => 61)
      student11.test_results.create!(:main_test_id => test.id, :marks => 59)
      student12.test_results.create!(:main_test_id => test.id, :marks => 49)
      student13.test_results.create!(:main_test_id => test.id, :marks => 70)
      student14.test_results.create!(:main_test_id => test.id, :marks => 77)
      student15.test_results.create!(:main_test_id => test.id, :marks => 47)
      student16.test_results.create!(:main_test_id => test.id, :marks => 78)
      student17.test_results.create!(:main_test_id => test.id, :marks => 77)
      student18.test_results.create!(:main_test_id => test.id, :marks => 43)
      student19.test_results.create!(:main_test_id => test.id, :marks => 48)
      student20.test_results.create!(:main_test_id => test.id, :marks => 43)
    when "fa2"
      student1.test_results.create!(:main_test_id => test.id, :marks => 80)
      student2.test_results.create!(:main_test_id => test.id, :marks => 78)
      student3.test_results.create!(:main_test_id => test.id, :marks => 76)
      student4.test_results.create!(:main_test_id => test.id, :marks => 88)
      student5.test_results.create!(:main_test_id => test.id, :marks => 77)
      student6.test_results.create!(:main_test_id => test.id, :marks => 83)
      student7.test_results.create!(:main_test_id => test.id, :marks => 48)
      student8.test_results.create!(:main_test_id => test.id, :marks => 51)
      student9.test_results.create!(:main_test_id => test.id, :marks => 61)
      student10.test_results.create!(:main_test_id => test.id, :marks => 77)
      student11.test_results.create!(:main_test_id => test.id, :marks => 58)
      student12.test_results.create!(:main_test_id => test.id, :marks => 44)
      student13.test_results.create!(:main_test_id => test.id, :marks => 73)
      student14.test_results.create!(:main_test_id => test.id, :marks => 32)
      student15.test_results.create!(:main_test_id => test.id, :marks => 40)
      student16.test_results.create!(:main_test_id => test.id, :marks => 87)
      student17.test_results.create!(:main_test_id => test.id, :marks => 39)
      student18.test_results.create!(:main_test_id => test.id, :marks => 44)
      student19.test_results.create!(:main_test_id => test.id, :marks => 87)
      student20.test_results.create!(:main_test_id => test.id, :marks => 79)
    when "sa1"
      student1.test_results.create!(:main_test_id => test.id, :marks => 62)
      student2.test_results.create!(:main_test_id => test.id, :marks => 50)
      student3.test_results.create!(:main_test_id => test.id, :marks => 64)
      student4.test_results.create!(:main_test_id => test.id, :marks => 65)
      student5.test_results.create!(:main_test_id => test.id, :marks => 51)
      student6.test_results.create!(:main_test_id => test.id, :marks => 58)
      student7.test_results.create!(:main_test_id => test.id, :marks => 65)
      student8.test_results.create!(:main_test_id => test.id, :marks => 50)
      student9.test_results.create!(:main_test_id => test.id, :marks => 33)
      student10.test_results.create!(:main_test_id => test.id, :marks => 22)
      student11.test_results.create!(:main_test_id => test.id, :marks => 90)
      student12.test_results.create!(:main_test_id => test.id, :marks => 73)
      student13.test_results.create!(:main_test_id => test.id, :marks => 30)
      student14.test_results.create!(:main_test_id => test.id, :marks => 34)
      student15.test_results.create!(:main_test_id => test.id, :marks => 35)
      student16.test_results.create!(:main_test_id => test.id, :marks => 81)
      student17.test_results.create!(:main_test_id => test.id, :marks => 83)
      student18.test_results.create!(:main_test_id => test.id, :marks => 35)
      student19.test_results.create!(:main_test_id => test.id, :marks => 31)
      student20.test_results.create!(:main_test_id => test.id, :marks => 45)
    end
  end

end
